aeropuerto/asp_presentacion/Pages/Ventanas/Aviones.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class AvionesModel : PageModel
    {
        private IAvionesPresentacion? iPresentacion = null;
        private IPilotosPresentacion? iPilotosPresentacion = null;

        public AvionesModel(IAvionesPresentacion iPresentacion,
            IPilotosPresentacion iPilotosPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                this.iPilotosPresentacion = iPilotosPresentacion;
                Filtro = new Aviones();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Aviones? Actual { get; set; }
        [BindProperty] public Aviones? Filtro { get; set; }
        [BindProperty] public List<Aviones>? Lista { get; set; }
        [BindProperty] public List<Pilotos>? Pilotos { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("Usuario");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.Codigo = Filtro!.Codigo ?? "";

                Accion = Enumerables.Ventanas.Listas;

                var task = this.iPresentacion!.PorCodigo(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        private void CargarCombox()
        {
            try
            {
                var task = this.iPilotosPresentacion!.Listar();
                task.Wait();
                Pilotos = task.Result;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Aviones();
                CargarCombox();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                CargarCombox();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;

                Task<Aviones>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

aeropuerto/asp_presentacion/Pages/Ventanas/Pilotos.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages.Ventanas
{
    public class PilotosModel : PageModel
    {
        private IPilotosPresentacion? iPresentacion = null;

        public PilotosModel(IPilotosPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Pilotos();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Pilotos? Actual { get; set; }
        [BindProperty] public Pilotos? Filtro { get; set; }
        [BindProperty] public List<Pilotos>? Lista { get; set; }

        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                var variable_session = HttpContext.Session.GetString("Usuario");
                if (String.IsNullOrEmpty(variable_session))
                {
                    HttpContext.Response.Redirect("/");
                    return;
                }

                Filtro!.Cedula = Filtro!.Cedula ?? "";

                Accion = Enumerables.Ventanas.Listas;

                var task = this.iPresentacion!.PorCodigo(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Pilotos();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;

                Task<Pilotos>? task = null;
                if (Actual!.Id == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.Id.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

aeropuerto/asp_presentacion/Pages/Ventanas/Aviones.cshtml
@page
@model asp_presentacion.Pages.Ventanas.AvionesModel
@{
    ViewData["Titulo"] = "Aviones";
}
<center>
    <div>
        <form method="POST"
              enctype="multipart/form-data">
            @Html.AntiForgeryToken()

            <div align="left">
                <h3>Aviones</h3>
            </div>
            <div align="left"
                 class="bt_panel_buttons">
                <input type="submit"
                       value="Refrescar"
                       asp-page-handler="BtRefrescar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Nuevo"
                       asp-page-handler="BtNuevo"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Guardar"
                       asp-page-handler="BtGuardar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Cancelar"
                       asp-page-handler="BtCancelar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
            </div>

            @if (Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas ||
                 Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Id" />
            }
            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Codigo" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Modelo" />
                <input type="hidden"
                       asp-for="@Model.Actual!.FechaCompra" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Piloto" />
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Editar)
            {
                <div class="containers_vn panel panel-default">
                    <h3>Producto</h3>

                    <div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Codigo
                            </label>
                            <div class="col-lg-6">
                                <input id="nmCodigo"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Codigo" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Modelo
                            </label>
                            <div class="col-lg-6">
                                <input id="nmModelo"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Modelo" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                FechaCompra
                            </label>
                            <div class="col-lg-6">
                                <input id="nmFechaCompra"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.FechaCompra" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Piloto
                            </label>
                            <div class="col-lg-6">
                                <select id="nmPiloto"
                                    class="form-control"
                                        asp-for="@Model.Actual!.Piloto"
                                        asp-items="@(new SelectList(Model.Pilotos, "Id", "Nombre"))">
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            }

            @if (ViewData.ContainsKey("Mensaje"))
            {
                <input type="hidden"
                       asp-for="@Model.Accion" />
                @await Html.PartialAsync("../Emergentes/Mensajes.cshtml")
                ;
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">
                                Mensaje
                            </h2>

                            <h4 align="left">
                                Desea borrar la entidad?
                            </h4>
                            <h6 align="left">
                                @Model.Actual!.Codigo,
                                @Model.Actual!.Modelo
                            </h6>
                            <br />
                            <br />
                            <input type="submit"
                                   value="Borrar"
                                   asp-page-handler="BtBorrar"
                                   class="btn btn-secondary" />
                            <input type="submit"
                                   value="Cerrar"
                                   asp-page-handler="BtCancelar"
                                   class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas ||
                 Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input id="flCodigo"
                       class="cts_forms form-control"
                       asp-for="@Model.Filtro!.Codigo"
                       placeholder="Codigo" />
                <br />

                <div class="containers_vn panel panel-default">
                    <table class="tb_data table table-striped table-bordered table-hover">
                        <tr>
                            <th>
                                Codigo
                            </th>
                            <th>
                                Modelo
                            </th>
                            <th class="cl_hidden">
                                FechaCompra
                            </th>
                            <th class="cl_actions">
                                Piloto
                            </th>
                            <th>
                                Accion
                            </th>
                        </tr>
                        @if (Model != null && Model.Lista != null)
                        {
                            @foreach (var elemento in Model.Lista)
                            {
                                <tr>
                                    <td>
                                        @elemento.Codigo
                                    </td>
                                    <td>
                                        @elemento.Modelo
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento.FechaCompra
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento._Piloto!.Nombre
                                    </td>
                                    <td>
                                        <input type="submit"
                                               value="Modicar"
                                               asp-page-handler="BtModificar"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                        <input type="submit"
                                               value="Borrar"
                                               asp-page-handler="BtBorrarVal"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            }
        </form>
    </div>
</center>

aeropuerto/asp_presentacion/Pages/Ventanas/Pilotos.cshtml
@page
@model asp_presentacion.Pages.Ventanas.PilotosModel
@{
	ViewData["Titulo"] = "Pilotos";
}
<center>
	<div>
		<form method="post"
			enctype="multipart/form-data">
			@Html.AntiForgeryToken()
			<div align="left">
				<h3>Pilotos</h3>
			</div>
            <div align="left"
                 class="bt_panel_buttons">
                <input type="submit"
                       value="Refrescar"
                       asp-page-handler="BtRefrescar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Nuevo"
                       asp-page-handler="BtNuevo"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Guardar"
                       asp-page-handler="BtGuardar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
                <input type="submit"
                       value="Cancelar"
                       asp-page-handler="BtCancelar"
                       class="btn btn-secondary"
                       disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)" />
            </div>

            @if (Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas ||
            Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Id" />
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input type="hidden"
                       asp-for="@Model.Actual!.Cedula" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Nombre" />
                <input type="hidden"
                       asp-for="@Model.Actual!.Pago" />
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Editar)
            {
                <div class="containers_vn panel panel-default">
                    <h3>Piloto</h3>

                    <div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Cedula
                            </label>
                            <div class="col-lg-6">
                                <input id="nmCedula"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Cedula" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Nombre
                            </label>
                            <div class="col-lg-6">
                                <input id="nmNombre"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Nombre" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">
                                Pago
                            </label>
                            <div class="col-lg-6">
                                <input id="nmPago"
                                       class="cts_forms form-control"
                                       asp-for="@Model.Actual!.Pago" />
                            </div>
                        </div>                       
                    </div>
                </div>
            }

            @if (ViewData.ContainsKey("Mensaje"))
            {
                <input type="hidden"
                       asp-for="@Model.Accion" />
                @await Html.PartialAsync("../Emergentes/Mensajes.cshtml");
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <div class='popup'>
                    <div class='pp_del_inner'>
                        <div style='width:95%'>
                            <h2 align="left">
                                Mensaje
                            </h2>

                            <h4 align="left">
                                Desea borrar la entidad?
                            </h4>
                            <h6 align="left">
                                @Model.Actual!.Cedula,
                                @Model.Actual!.Nombre
                            </h6>
                            <br />
                            <br />
                            <input type="submit"
                                   value="Borrar"
                                   asp-page-handler="BtBorrar"
                                   class="btn btn-secondary" />
                            <input type="submit"
                                   value="Cerrar"
                                   asp-page-handler="BtCancelar"
                                   class="btn btn-secondary" />
                        </div>
                    </div>
                </div>
            }

            @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas ||
            Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
            {
                <input id="flCedula"
                       class="cts_forms form-control"
                       asp-for="@Model.Filtro!.Cedula"
                       placeholder="Cedula" />
                <br />

                <div class="containers_vn panel panel-default">
                    <table class="tb_data table table-striped table-bordered table-hover">
                        <tr>
                            <th>
                                Cedula
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th class="cl_hidden">
                                Pago
                            </th>
                            <th>
                                Accion
                            </th>
                        </tr>
                        @if (Model != null && Model.Lista != null)
                        {
                            @foreach (var elemento in Model.Lista)
                            {
                                <tr>
                                    <td>
                                        @elemento.Cedula
                                    </td>
                                    <td>
                                        @elemento.Nombre
                                    </td>
                                    <td class="cl_hidden">
                                        @elemento.Pago
                                    </td>
                                    <td>
                                        <input type="submit"
                                               value="Modicar"
                                               asp-page-handler="BtModificar"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                        <input type="submit"
                                               value="Borrar"
                                               asp-page-handler="BtBorrarVal"
                                               class="btn btn-secondary"
                                               asp-route-data="@elemento.Id" />
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            }

		</form>
	</div>
</center>