aeropuerto/asp_presentacion/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

aeropuerto/asp_presentacion/Pages/Index.cshtml.cs
using lib_dominio.Nucleo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class IndexModel : PageModel
    {
        public bool EstaLogueado = false;
        [BindProperty] public string? Email { get; set; }
        [BindProperty] public string? Contrasena { get; set; }

        public void OnGet()
        {
            var variable_session = HttpContext.Session.GetString("Usuario");
            if (!String.IsNullOrEmpty(variable_session))
            {
                EstaLogueado = true;
                return;
            }
        }

        public void OnPostBtClean()
        {
            try
            {
                Email = string.Empty;
                Contrasena = string.Empty;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtEnter()
        {
            try
            {
                if (string.IsNullOrEmpty(Email) &&
                    string.IsNullOrEmpty(Contrasena))
                {
                    OnPostBtClean();
                    return;
                }

                if ("admin.123" != Email + "." + Contrasena)
                {
                    OnPostBtClean();
                    return;
                }
                ViewData["Logged"] = true;
                HttpContext.Session.SetString("Usuario", Email!);
                EstaLogueado = true;
                OnPostBtClean();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtClose()
        {
            try
            {
                HttpContext.Session.Clear();
                HttpContext.Response.Redirect("/");
                EstaLogueado = false;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

aeropuerto/asp_presentacion/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace asp_presentacion.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

aeropuerto/asp_presentacion/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "";
}
@if (!Model.EstaLogueado)
{
    <div class="container"
         align="left"
         style="width:100%">
        <h3>
            Login
        </h3>

        <form method="POST">
            <div style="width:60%">
                <div class="form-group">
                    <label class="control-label">
                        Usuario:
                    </label>
                    <input onchange="keyUp(this)"
                           asp-for="@Model.Email"
                           class="form-control" />
                </div>
                <div class="form-group">
                    <label class="control-label">
                        Contrasena:
                    </label>
                    <input type="password"
                           onchange="keyUp(this)"
                           asp-for="@Model.Contrasena"
                           class="form-control" />
                </div>

                <input type="submit"
                       value="Limpiar"
                       asp-page-handler="BtClean"
                       class="btn btn-default" />
                <input type="submit"
                       value="Entrar"
                       asp-page-handler="BtEnter"
                       class="btn btn-default" />
            </div>
        </form>
    </div>
}
else
{
    <div class="text-center">
        <h1 class="display-4">
            Bienvenido
        </h1>

        <form method="POST">
            <input type="submit"
                   value="Cerrar"
                   asp-page-handler="BtClose"
                   class="btn btn-default" />
        </form>
    </div>
}